#!/bin/sh

# Prevent Git push operations from succeeding if branch paths contain `master`.
#
# Based on Git's pre-push sample which can be found here:
# https://github.com/git/git/blob/v2.27.0/templates/hooks--pre-push.sample
#
# Called by "git push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	# The test operator: !=
	# Performs an "is not equal to" string comparison.
	if [ "$local_sha" != $z40 ]
	then
		# This is not a delete operation.

		# Checking if a string contains a substring:
		# https://stackoverflow.com/a/229606/392847

		if [[ $local_ref == *"master"* ]]; then
			echo >&2 "Found string 'master' in local reference $local_ref. Rejecting git push."
			exit 1
		fi

		if [[ $remote_ref == *"master"* ]]; then
			echo >&2 "Found string 'master' in remote reference $remote_ref. Rejecting git push."
			exit 1
		fi
	fi
done

exit 0
